persistence true
persistence_location /mosquitto/data/

persistence_file mosquitto.db

log_dest stdout
log_dest file /mosquitto/log/mosquitto.log

per_listener_settings true
allow_anonymous false
password_file /mosquitto/config/passwordfile

listener 8883
protocol mqtt
certfile /mosquitto/certs/fullchain.pem
keyfile /mosquitto/certs/privkey.pem
tls_version tlsv1.2
require_certificate false

# Optional hardening
# Set to true only if you want mutual TLS client certificates in addition to username/password.
# require_certificate true
