# Sensor Station 1 mit ENV-III
# mit WLAN BSZ-Schueler
# sendet an mqtt (test.mosquitto.org),
# abonniert Temperatur von Station 2
# Statusanzeige über Display (grün, gelb, rot, Initialisierung blau)

esphome:
  name: "atoms3r-fisi-unit-01" # Bitte hier Nummer der Gruppe eintragen!
  friendly_name: "BSZ Sensor Station 01" # Bitte hier Nummer der Gruppe eintragen!

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino

logger:
  level: DEBUG
  
globals:
  - id: mqtt_temp
    type: float
    restore_value: false
    initial_value: "0.0"

# Lädt den Community-Treiber für den I2C-LED-Chip herunter
external_components:
  - source:
      type: git
      url: https://github.com/ssieb/esphome
      ref: lp5562
    components: [ lp5562 ]

wifi:



# ==========================================
# I2C BUSSE (INTERN & EXTERN TRENNEN!)
# ==========================================
i2c:
  # 1. Der INTERNE Bus des AtomS3R für das Display-Licht
  - id: i2c_internal
    sda: GPIO45
    scl: GPIO0
    scan: true

  # 2. Der EXTERNE Bus (Grove-Port) für den ENV III Sensor
  - id: i2c_external
    sda: 2
    scl: 1
    scan: true

# Den LP5562-Chip auf den internen Bus registrieren
lp5562:
  - i2c_id: i2c_internal

output:
  - platform: lp5562
    id: backlight_output
    channel: 3 

light:
  - platform: monochromatic
    output: backlight_output
    name: "AtomS3R Display Backlight"
    id: atom_backlight
    restore_mode: ALWAYS_ON

spi:
  clk_pin: GPIO15
  mosi_pin: GPIO21

# ==========================================
# DISPLAY & MQTT LOGIK
# ==========================================
display:
  - platform: st7789v
    id: oled_display
    model: CUSTOM
    width: 128
    height: 128
    offset_width: 2
    offset_height: 1
    cs_pin: GPIO14  
    dc_pin: GPIO42  
    reset_pin: GPIO48 
    rotation: 0
    update_interval: 1s
    lambda: |-
      // Variable auslesen
      float temp = id(mqtt_temp);
      # Hier kommen die Bedingungen und Aktionen hin! ================
      if (temp == 0.0) {
        // Startwert, wenn noch keine MQTT-Nachricht da ist
        it.fill(Color(0, 0, 255)); // BLAU
      } else if (...) {
        it.fill(Color(...)); // GRÜN
      } else if (...) {
        it.fill(Color(...)); // GELB 
      } else {
        it.fill(Color(....)); // ROT
      }

mqtt:
  broker: "152.53.144.73"
  port: 1883
  topic_prefix: "BSZ/E2FI2/Unit-01"  # <===== Bitte hier Nummer der Gruppe eintragen!
  on_message:
     # Bitte hier Nummer bzw. Topic der PARTNER-Gruppe eintragen!
    - topic: "BSZ/E2FI2/Unit-01/sensor/raumtemperatur/state"
      then:
        - lambda: |-
            // Wert aus MQTT empfangen, konvertieren und in Globale Variable schreiben
            float temp = atof(x.c_str());
            id(mqtt_temp) = temp;
            ESP_LOGI("mqtt", "Empfangene Temperatur: %.2f °C", temp);

# ==========================================
# SENSOREN
# ==========================================
sensor:


binary_sensor:
 